### ISSUE TITLE
3mm Resolution Template has 0.5mm Resolution

### ISSUE THREAD

**Issue by ellisdg** [templateflow/tpl-MNI152NLin6Asym#5]
I'm not sure if this is the right place to post this, but when I download the 3mm MNI152NLin6Asym template the spacing is actually 0.5 mm instead of 3mm.

I even tried downloading it directly from AWS:
https://templateflow.s3.amazonaws.com/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-03_T1w.nii.gz

Output from fslinfo:

**data_type	INT16
dim1		364
dim2		436
dim3		364
dim4		1
datatype	4
pixdim1		0.500000
pixdim2		0.500000
pixdim3		0.500000
pixdim4		1.000000
cal_max		250.000000
cal_min		0.000000
file_type	NIFTI-1+**

I assume this is some sort of mistake, but let me know I'm wrong and I just don't understand how the templateflow resolutions work.

**Comment by effigies** [comment]
3 is an index, not a mm measurement. The metadata is where you should look for actual resolutions.

**Comment by ellisdg** [comment]
Thanks for the quick reply. What does a resolution index of 3 mean? Is there a dictionary somewhere for the definitions of the template descriptors?

**Comment by ellisdg** [comment]
Nevermind. I realize now that to see the resolutions you have to use the "templateflow.api.get_metadata" function for a specific template and then select the index for the desired resolution. Thanks for the help!
